public enum BuildingType
{
    LittleHouse,
    Road,
    BuildingSite,
    FastFoodRestaurant,
    Factory,
    Park,
    Lake,
    HomeownersAssociation,
    ConvenienceStore,
    Freeway,
    FancyRestaurant,
    Farm,
    Landfill,
    Mint,
    HouseTwoFloors,
    PublicTransportStop,
    OfficeBuilding
}